/* client.c generated by valac 0.26.2, the Vala compiler
 * generated from client.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_CLIENT (client_get_type ())
#define CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLIENT, Client))
#define CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLIENT, ClientClass))
#define IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLIENT))
#define IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLIENT))
#define CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLIENT, ClientClass))

typedef struct _Client Client;
typedef struct _ClientClass ClientClass;
typedef struct _ClientPrivate ClientPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))

struct _Client {
	GObject parent_instance;
	ClientPrivate * priv;
	GDataInputStream* input_stream;
	GDataOutputStream* output_stream;
	gint tab;
	gchar* username;
};

struct _ClientClass {
	GObjectClass parent_class;
};

struct _ClientPrivate {
	gchar* url;
};


static gpointer client_parent_class = NULL;

GType client_get_type (void) G_GNUC_CONST;
#define CLIENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CLIENT, ClientPrivate))
enum  {
	CLIENT_DUMMY_PROPERTY
};
gboolean client_connect_to_server (Client* self, const gchar* location, gint tab_page);
static gint client_do_connect (Client* self);
static gpointer _client_do_connect_gthread_func (gpointer self);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
void client_send_output (Client* self, const gchar* output);
Client* client_new (void);
Client* client_construct (GType object_type);
static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void client_finalize (GObject* obj);


static gpointer _client_do_connect_gthread_func (gpointer self) {
	gpointer result;
	result = (gpointer) ((gintptr) client_do_connect ((Client*) self));
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_object_unref (self);
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return result;
#line 72 "client.c"
}


gboolean client_connect_to_server (Client* self, const gchar* location, gint tab_page) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GError * _inner_error_ = NULL;
#line 16 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 16 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_val_if_fail (location != NULL, FALSE);
#line 18 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = location;
#line 18 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 18 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (self->priv->url);
#line 18 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->priv->url = _tmp1_;
#line 19 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = tab_page;
#line 19 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->tab = _tmp2_;
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_thread_create (_client_do_connect_gthread_func, g_object_ref (self), TRUE, &_inner_error_);
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return FALSE;
#line 108 "client.c"
	}
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
	result = TRUE;
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return result;
#line 114 "client.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return self ? g_object_ref (self) : NULL;
#line 121 "client.c"
}


static void _g_object_unref0_ (gpointer var) {
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 128 "client.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_list_free (self);
#line 137 "client.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 1115 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1116 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1116 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1117 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1117 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1118 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = _result_;
#line 1118 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 160 "client.c"
}


static gint client_do_connect (Client* self) {
	gint result = 0;
	GSocketClient* client = NULL;
	GSocketClient* _tmp0_ = NULL;
	GResolver* resolver = NULL;
	GResolver* _tmp1_ = NULL;
	GList* addresses = NULL;
	GResolver* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	GInetAddress* address = NULL;
	GList* _tmp5_ = NULL;
	gconstpointer _tmp6_ = NULL;
	GInetAddress* _tmp7_ = NULL;
	FILE* _tmp8_ = NULL;
	GInetAddress* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	GSocketConnection* conn = NULL;
	GSocketClient* _tmp14_ = NULL;
	GInetAddress* _tmp15_ = NULL;
	GInetSocketAddress* _tmp16_ = NULL;
	GInetSocketAddress* _tmp17_ = NULL;
	GSocketConnection* _tmp18_ = NULL;
	GSocketConnection* _tmp19_ = NULL;
	GSocketConnection* _tmp20_ = NULL;
	GInputStream* _tmp21_ = NULL;
	GInputStream* _tmp22_ = NULL;
	GDataInputStream* _tmp23_ = NULL;
	GSocketConnection* _tmp24_ = NULL;
	GOutputStream* _tmp25_ = NULL;
	GOutputStream* _tmp26_ = NULL;
	GDataOutputStream* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	gchar* line = NULL;
	gchar* _tmp39_ = NULL;
	GError * _inner_error_ = NULL;
#line 26 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 28 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = g_socket_client_new ();
#line 28 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client = _tmp0_;
#line 31 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = g_resolver_get_default ();
#line 31 "/home/stack/Apps/projects/KyRC/src/client.vala"
	resolver = _tmp1_;
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = resolver;
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp3_ = self->priv->url;
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp4_ = g_resolver_lookup_by_name (_tmp2_, _tmp3_, NULL, &_inner_error_);
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
	addresses = _tmp4_;
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (resolver);
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (client);
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 32 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return 0;
#line 243 "client.c"
	}
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp5_ = addresses;
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp6_ = g_list_nth_data (_tmp5_, (guint) 0);
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp7_ = _g_object_ref0 ((GInetAddress*) _tmp6_);
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	address = _tmp7_;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp8_ = stderr;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp9_ = address;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp10_ = g_inet_address_to_string (_tmp9_);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp11_ = _tmp10_;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp12_ = g_strconcat ("address ", _tmp11_, NULL);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp13_ = _tmp12_;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	fprintf (_tmp8_, "%s", _tmp13_);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp13_);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp11_);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp14_ = client;
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp15_ = address;
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp16_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp15_, (guint16) 6667);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp17_ = _tmp16_;
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp18_ = g_socket_client_connect (_tmp14_, (GSocketConnectable*) _tmp17_, NULL, &_inner_error_);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp19_ = _tmp18_;
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (_tmp17_);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	conn = _tmp19_;
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (address);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		__g_list_free__g_object_unref0_0 (addresses);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (resolver);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (client);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return 0;
#line 303 "client.c"
	}
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp20_ = conn;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp21_ = g_io_stream_get_input_stream ((GIOStream*) _tmp20_);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp22_ = _tmp21_;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp23_ = g_data_input_stream_new (_tmp22_);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->input_stream);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->input_stream = _tmp23_;
#line 38 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp24_ = conn;
#line 38 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp25_ = g_io_stream_get_output_stream ((GIOStream*) _tmp24_);
#line 38 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp26_ = _tmp25_;
#line 38 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp27_ = g_data_output_stream_new (_tmp26_);
#line 38 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->output_stream);
#line 38 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->output_stream = _tmp27_;
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp28_ = self->username;
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp29_ = g_strconcat ("NICK ", _tmp28_, NULL);
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp30_ = _tmp29_;
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client_send_output (self, _tmp30_);
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp30_);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp31_ = self->username;
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp32_ = g_strconcat ("USER ", _tmp31_, NULL);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp33_ = _tmp32_;
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp34_ = g_strconcat (_tmp33_, " null null :", NULL);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp35_ = _tmp34_;
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp36_ = self->username;
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp37_ = g_strconcat (_tmp35_, _tmp36_, NULL);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp38_ = _tmp37_;
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client_send_output (self, _tmp38_);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp38_);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp35_);
#line 41 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp33_);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp39_ = g_strdup ("");
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	line = _tmp39_;
#line 367 "client.c"
	{
		gboolean _tmp40_ = FALSE;
#line 44 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_tmp40_ = TRUE;
#line 44 "/home/stack/Apps/projects/KyRC/src/client.vala"
		while (TRUE) {
#line 374 "client.c"
			gchar* _tmp42_ = NULL;
			GDataInputStream* _tmp43_ = NULL;
			gchar* _tmp44_ = NULL;
			gchar* _tmp45_ = NULL;
			gchar* _tmp46_ = NULL;
			gchar* _tmp47_ = NULL;
			gchar* _tmp48_ = NULL;
			gchar* _tmp49_ = NULL;
			FILE* _tmp50_ = NULL;
			const gchar* _tmp51_ = NULL;
			gchar* _tmp52_ = NULL;
			gchar* _tmp53_ = NULL;
			gint _tmp54_ = 0;
			const gchar* _tmp55_ = NULL;
#line 44 "/home/stack/Apps/projects/KyRC/src/client.vala"
			if (!_tmp40_) {
#line 391 "client.c"
				const gchar* _tmp41_ = NULL;
#line 48 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_tmp41_ = line;
#line 48 "/home/stack/Apps/projects/KyRC/src/client.vala"
				if (!(_tmp41_ != NULL)) {
#line 48 "/home/stack/Apps/projects/KyRC/src/client.vala"
					break;
#line 399 "client.c"
				}
			}
#line 44 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp40_ = FALSE;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp43_ = self->input_stream;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp44_ = g_data_input_stream_read_line (_tmp43_, NULL, NULL, &_inner_error_);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp42_ = _tmp44_;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_free0 (line);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (conn);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (address);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				__g_list_free__g_object_unref0_0 (addresses);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (resolver);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (client);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				g_clear_error (&_inner_error_);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
				return 0;
#line 430 "client.c"
			}
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp45_ = _tmp42_;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp42_ = NULL;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp46_ = _tmp45_;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp47_ = string_strip (_tmp46_);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp48_ = _tmp47_;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp49_ = g_strconcat (_tmp48_, "\n", NULL);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (line);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			line = _tmp49_;
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp48_);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp46_);
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp50_ = stderr;
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp51_ = line;
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp52_ = g_strconcat ("line ", _tmp51_, NULL);
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp53_ = _tmp52_;
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			fprintf (_tmp50_, "%s", _tmp53_);
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp53_);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp54_ = self->tab;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp55_ = line;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			g_signal_emit_by_name (self, "new-data", _tmp54_, _tmp55_);
#line 44 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp42_);
#line 472 "client.c"
		}
	}
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	result = 1;
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (line);
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (conn);
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (address);
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	__g_list_free__g_object_unref0_0 (addresses);
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (resolver);
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (client);
#line 50 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return result;
#line 491 "client.c"
}


void client_send_output (Client* self, const gchar* output) {
	GDataOutputStream* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 53 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (self != NULL);
#line 53 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (output != NULL);
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = self->output_stream;
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = output;
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = g_strconcat (_tmp1_, "\r\n", NULL);
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp3_ = _tmp2_;
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_data_output_stream_put_string (_tmp0_, _tmp3_, NULL, &_inner_error_);
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp3_);
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return;
#line 525 "client.c"
	}
}


Client* client_construct (GType object_type) {
	Client * self = NULL;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self = (Client*) g_object_new (object_type, NULL);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return self;
#line 536 "client.c"
}


Client* client_new (void) {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return client_construct (TYPE_CLIENT);
#line 543 "client.c"
}


static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__INT_STRING) (gpointer data1, gint arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (n_param_values == 3);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data1 = closure->data;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data2 = param_values->data[0].v_pointer;
#line 562 "client.c"
	} else {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data1 = param_values->data[0].v_pointer;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data2 = closure->data;
#line 568 "client.c"
	}
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	callback = (GMarshalFunc_VOID__INT_STRING) (marshal_data ? marshal_data : cc->callback);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	callback (data1, g_value_get_int (param_values + 1), g_value_get_string (param_values + 2), data2);
#line 574 "client.c"
}


static void client_class_init (ClientClass * klass) {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client_parent_class = g_type_class_peek_parent (klass);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_type_class_add_private (klass, sizeof (ClientPrivate));
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	G_OBJECT_CLASS (klass)->finalize = client_finalize;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_signal_new ("new_data", TYPE_CLIENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT_STRING, G_TYPE_NONE, 2, G_TYPE_INT, G_TYPE_STRING);
#line 587 "client.c"
}


static void client_instance_init (Client * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->priv = CLIENT_GET_PRIVATE (self);
#line 9 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = g_strdup ("");
#line 9 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->priv->url = _tmp0_;
#line 11 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = g_strdup ("");
#line 11 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->username = _tmp1_;
#line 604 "client.c"
}


static void client_finalize (GObject* obj) {
	Client * self;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CLIENT, Client);
#line 7 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->input_stream);
#line 8 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->output_stream);
#line 9 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (self->priv->url);
#line 11 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (self->username);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	G_OBJECT_CLASS (client_parent_class)->finalize (obj);
#line 622 "client.c"
}


GType client_get_type (void) {
	static volatile gsize client_type_id__volatile = 0;
	if (g_once_init_enter (&client_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClientClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) client_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Client), 0, (GInstanceInitFunc) client_instance_init, NULL };
		GType client_type_id;
		client_type_id = g_type_register_static (G_TYPE_OBJECT, "Client", &g_define_type_info, 0);
		g_once_init_leave (&client_type_id__volatile, client_type_id);
	}
	return client_type_id__volatile;
}



