/* client.c generated by valac 0.26.2, the Vala compiler
 * generated from client.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_CLIENT (client_get_type ())
#define CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLIENT, Client))
#define CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLIENT, ClientClass))
#define IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLIENT))
#define IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLIENT))
#define CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLIENT, ClientClass))

typedef struct _Client Client;
typedef struct _ClientClass ClientClass;
typedef struct _ClientPrivate ClientPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _Client {
	GObject parent_instance;
	ClientPrivate * priv;
	GDataInputStream* input_stream;
	GDataOutputStream* output_stream;
	gint tab;
	gchar* username;
	gboolean exit;
};

struct _ClientClass {
	GObjectClass parent_class;
};

struct _ClientPrivate {
	gchar* url;
};


static gpointer client_parent_class = NULL;

GType client_get_type (void) G_GNUC_CONST;
#define CLIENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CLIENT, ClientPrivate))
enum  {
	CLIENT_DUMMY_PROPERTY
};
#define CLIENT_default_port ((guint16) 6667)
gboolean client_connect_to_server (Client* self, const gchar* location, gint tab_page);
static gint client_do_connect (Client* self);
static gpointer _client_do_connect_gthread_func (gpointer self);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
void client_send_output (Client* self, const gchar* output);
void client_stop (Client* self);
Client* client_new (void);
Client* client_construct (GType object_type);
static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void client_finalize (GObject* obj);


static gpointer _client_do_connect_gthread_func (gpointer self) {
	gpointer result;
	result = (gpointer) ((gintptr) client_do_connect ((Client*) self));
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_object_unref (self);
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return result;
#line 76 "client.c"
}


gboolean client_connect_to_server (Client* self, const gchar* location, gint tab_page) {
	gboolean result = FALSE;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GError * _inner_error_ = NULL;
#line 18 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 18 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_val_if_fail (location != NULL, FALSE);
#line 20 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = location;
#line 20 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 20 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (self->priv->url);
#line 20 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->priv->url = _tmp1_;
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = tab_page;
#line 21 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->tab = _tmp2_;
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_thread_create (_client_do_connect_gthread_func, g_object_ref (self), TRUE, &_inner_error_);
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 23 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return FALSE;
#line 112 "client.c"
	}
#line 25 "/home/stack/Apps/projects/KyRC/src/client.vala"
	result = TRUE;
#line 25 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return result;
#line 118 "client.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return self ? g_object_ref (self) : NULL;
#line 125 "client.c"
}


static void _g_object_unref0_ (gpointer var) {
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
#line 132 "client.c"
}


static void _g_list_free__g_object_unref0_ (GList* self) {
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_list_free (self);
#line 141 "client.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 1115 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1116 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1116 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1117 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1117 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1118 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = _result_;
#line 1118 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 164 "client.c"
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 1197 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = str;
#line 1197 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = maxlen;
#line 1197 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
#line 1197 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	end = _tmp2_;
#line 1198 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp3_ = end;
#line 1198 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	if (_tmp3_ == NULL) {
#line 187 "client.c"
		glong _tmp4_ = 0L;
#line 1199 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp4_ = maxlen;
#line 1199 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		result = _tmp4_;
#line 1199 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		return result;
#line 195 "client.c"
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
#line 1201 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp5_ = end;
#line 1201 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp6_ = str;
#line 1201 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		result = (glong) (_tmp5_ - _tmp6_);
#line 1201 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		return result;
#line 207 "client.c"
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
#line 1208 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1210 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = offset;
#line 1210 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	if (_tmp1_ >= ((glong) 0)) {
#line 231 "client.c"
		glong _tmp2_ = 0L;
#line 1210 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp2_ = len;
#line 1210 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp0_ = _tmp2_ >= ((glong) 0);
#line 237 "client.c"
	} else {
#line 1210 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 241 "client.c"
	}
#line 1210 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	if (_tmp0_) {
#line 245 "client.c"
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
#line 1212 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp3_ = offset;
#line 1212 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp4_ = len;
#line 1212 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
#line 1212 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		string_length = _tmp5_;
#line 257 "client.c"
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
#line 1214 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp6_ = strlen (self);
#line 1214 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp7_ = _tmp6_;
#line 1214 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		string_length = (glong) _tmp7_;
#line 267 "client.c"
	}
#line 1217 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp8_ = offset;
#line 1217 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	if (_tmp8_ < ((glong) 0)) {
#line 273 "client.c"
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
#line 1218 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp9_ = string_length;
#line 1218 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp10_ = offset;
#line 1218 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		offset = _tmp9_ + _tmp10_;
#line 1219 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp11_ = offset;
#line 1219 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
#line 287 "client.c"
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
#line 1221 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp12_ = offset;
#line 1221 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp13_ = string_length;
#line 1221 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
#line 297 "client.c"
	}
#line 1223 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp14_ = len;
#line 1223 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	if (_tmp14_ < ((glong) 0)) {
#line 303 "client.c"
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
#line 1224 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp15_ = string_length;
#line 1224 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		_tmp16_ = offset;
#line 1224 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
		len = _tmp15_ - _tmp16_;
#line 312 "client.c"
	}
#line 1226 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp17_ = offset;
#line 1226 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp18_ = len;
#line 1226 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp19_ = string_length;
#line 1226 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
#line 1227 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp20_ = offset;
#line 1227 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp21_ = len;
#line 1227 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
#line 1227 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = _tmp22_;
#line 1227 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 332 "client.c"
}


static gint client_do_connect (Client* self) {
	gint result = 0;
	GSocketClient* client = NULL;
	GSocketClient* _tmp0_ = NULL;
	GResolver* resolver = NULL;
	GResolver* _tmp1_ = NULL;
	GList* addresses = NULL;
	GResolver* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	GList* _tmp4_ = NULL;
	GInetAddress* address = NULL;
	GList* _tmp5_ = NULL;
	gconstpointer _tmp6_ = NULL;
	GInetAddress* _tmp7_ = NULL;
	FILE* _tmp8_ = NULL;
	GInetAddress* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	GSocketConnection* conn = NULL;
	GSocketClient* _tmp14_ = NULL;
	GInetAddress* _tmp15_ = NULL;
	GInetSocketAddress* _tmp16_ = NULL;
	GInetSocketAddress* _tmp17_ = NULL;
	GSocketConnection* _tmp18_ = NULL;
	GSocketConnection* _tmp19_ = NULL;
	GSocketConnection* _tmp20_ = NULL;
	GInputStream* _tmp21_ = NULL;
	GInputStream* _tmp22_ = NULL;
	GDataInputStream* _tmp23_ = NULL;
	GSocketConnection* _tmp24_ = NULL;
	GOutputStream* _tmp25_ = NULL;
	GOutputStream* _tmp26_ = NULL;
	GDataOutputStream* _tmp27_ = NULL;
	const gchar* _tmp28_ = NULL;
	gchar* _tmp29_ = NULL;
	gchar* _tmp30_ = NULL;
	const gchar* _tmp31_ = NULL;
	gchar* _tmp32_ = NULL;
	gchar* _tmp33_ = NULL;
	gchar* _tmp34_ = NULL;
	gchar* _tmp35_ = NULL;
	const gchar* _tmp36_ = NULL;
	gchar* _tmp37_ = NULL;
	gchar* _tmp38_ = NULL;
	gchar* line = NULL;
	gchar* _tmp39_ = NULL;
	GError * _inner_error_ = NULL;
#line 28 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 30 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = g_socket_client_new ();
#line 30 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client = _tmp0_;
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = g_resolver_get_default ();
#line 33 "/home/stack/Apps/projects/KyRC/src/client.vala"
	resolver = _tmp1_;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = resolver;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp3_ = self->priv->url;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp4_ = g_resolver_lookup_by_name (_tmp2_, _tmp3_, NULL, &_inner_error_);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	addresses = _tmp4_;
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (resolver);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (client);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 34 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return 0;
#line 415 "client.c"
	}
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp5_ = addresses;
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp6_ = g_list_nth_data (_tmp5_, (guint) 0);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp7_ = _g_object_ref0 ((GInetAddress*) _tmp6_);
#line 35 "/home/stack/Apps/projects/KyRC/src/client.vala"
	address = _tmp7_;
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp8_ = stderr;
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp9_ = address;
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp10_ = g_inet_address_to_string (_tmp9_);
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp11_ = _tmp10_;
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp12_ = g_strconcat ("address ", _tmp11_, NULL);
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp13_ = _tmp12_;
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	fprintf (_tmp8_, "%s", _tmp13_);
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp13_);
#line 36 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp11_);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp14_ = client;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp15_ = address;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp16_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp15_, CLIENT_default_port);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp17_ = _tmp16_;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp18_ = g_socket_client_connect (_tmp14_, (GSocketConnectable*) _tmp17_, NULL, &_inner_error_);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp19_ = _tmp18_;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (_tmp17_);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	conn = _tmp19_;
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (address);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		__g_list_free__g_object_unref0_0 (addresses);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (resolver);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_object_unref0 (client);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 37 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return 0;
#line 475 "client.c"
	}
#line 39 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp20_ = conn;
#line 39 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp21_ = g_io_stream_get_input_stream ((GIOStream*) _tmp20_);
#line 39 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp22_ = _tmp21_;
#line 39 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp23_ = g_data_input_stream_new (_tmp22_);
#line 39 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->input_stream);
#line 39 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->input_stream = _tmp23_;
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp24_ = conn;
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp25_ = g_io_stream_get_output_stream ((GIOStream*) _tmp24_);
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp26_ = _tmp25_;
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp27_ = g_data_output_stream_new (_tmp26_);
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->output_stream);
#line 40 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->output_stream = _tmp27_;
#line 42 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp28_ = self->username;
#line 42 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp29_ = g_strconcat ("NICK ", _tmp28_, NULL);
#line 42 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp30_ = _tmp29_;
#line 42 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client_send_output (self, _tmp30_);
#line 42 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp30_);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp31_ = self->username;
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp32_ = g_strconcat ("USER ", _tmp31_, NULL);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp33_ = _tmp32_;
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp34_ = g_strconcat (_tmp33_, " null null :", NULL);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp35_ = _tmp34_;
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp36_ = self->username;
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp37_ = g_strconcat (_tmp35_, _tmp36_, NULL);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp38_ = _tmp37_;
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client_send_output (self, _tmp38_);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp38_);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp35_);
#line 43 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp33_);
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp39_ = g_strdup ("");
#line 45 "/home/stack/Apps/projects/KyRC/src/client.vala"
	line = _tmp39_;
#line 539 "client.c"
	{
		gboolean _tmp40_ = FALSE;
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_tmp40_ = TRUE;
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
		while (TRUE) {
#line 546 "client.c"
			gchar* _tmp44_ = NULL;
			GDataInputStream* _tmp45_ = NULL;
			gchar* _tmp46_ = NULL;
			gchar* _tmp47_ = NULL;
			gchar* _tmp48_ = NULL;
			gchar* _tmp49_ = NULL;
			gchar* _tmp50_ = NULL;
			gchar* _tmp51_ = NULL;
			gint _tmp52_ = 0;
			const gchar* _tmp53_ = NULL;
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			if (!_tmp40_) {
#line 559 "client.c"
				gboolean _tmp41_ = FALSE;
				const gchar* _tmp42_ = NULL;
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_tmp42_ = line;
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
				if (_tmp42_ != NULL) {
#line 566 "client.c"
					gboolean _tmp43_ = FALSE;
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
					_tmp43_ = self->exit;
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
					_tmp41_ = !_tmp43_;
#line 572 "client.c"
				} else {
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
					_tmp41_ = FALSE;
#line 576 "client.c"
				}
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
				if (!_tmp41_) {
#line 49 "/home/stack/Apps/projects/KyRC/src/client.vala"
					break;
#line 582 "client.c"
				}
			}
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp40_ = FALSE;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp45_ = self->input_stream;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp46_ = g_data_input_stream_read_line (_tmp45_, NULL, NULL, &_inner_error_);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp44_ = _tmp46_;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_free0 (line);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (conn);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (address);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				__g_list_free__g_object_unref0_0 (addresses);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (resolver);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				_g_object_unref0 (client);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				g_clear_error (&_inner_error_);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
				return 0;
#line 613 "client.c"
			}
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp47_ = _tmp44_;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp44_ = NULL;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp48_ = _tmp47_;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp49_ = string_strip (_tmp48_);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp50_ = _tmp49_;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp51_ = string_substring (_tmp50_, (glong) 1, (glong) (-1));
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (line);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			line = _tmp51_;
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp50_);
#line 47 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp48_);
#line 48 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp52_ = self->tab;
#line 48 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_tmp53_ = line;
#line 48 "/home/stack/Apps/projects/KyRC/src/client.vala"
			g_signal_emit_by_name (self, "new-data", _tmp52_, _tmp53_);
#line 46 "/home/stack/Apps/projects/KyRC/src/client.vala"
			_g_free0 (_tmp44_);
#line 643 "client.c"
		}
	}
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	result = 1;
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (line);
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (conn);
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (address);
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	__g_list_free__g_object_unref0_0 (addresses);
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (resolver);
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (client);
#line 52 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return result;
#line 662 "client.c"
}


void client_stop (Client* self) {
	GDataInputStream* _tmp0_ = NULL;
	GDataOutputStream* _tmp2_ = NULL;
	GDataOutputStream* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 55 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (self != NULL);
#line 57 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->exit = TRUE;
#line 58 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = self->input_stream;
#line 58 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_input_stream_clear_pending ((GInputStream*) _tmp0_);
#line 679 "client.c"
	{
		GDataInputStream* _tmp1_ = NULL;
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_tmp1_ = self->input_stream;
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_input_stream_close ((GInputStream*) _tmp1_, NULL, &_inner_error_);
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
			if (_inner_error_->domain == G_IO_ERROR) {
#line 690 "client.c"
				goto __catch1_g_io_error;
			}
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
			g_clear_error (&_inner_error_);
#line 60 "/home/stack/Apps/projects/KyRC/src/client.vala"
			return;
#line 699 "client.c"
		}
	}
	goto __finally1;
	__catch1_g_io_error:
	{
		GError* e = NULL;
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
		e = _inner_error_;
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_inner_error_ = NULL;
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_error_free0 (e);
#line 712 "client.c"
	}
	__finally1:
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 59 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return;
#line 723 "client.c"
	}
#line 62 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = self->output_stream;
#line 62 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_output_stream_clear_pending ((GOutputStream*) _tmp2_);
#line 63 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp3_ = self->output_stream;
#line 63 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_output_stream_flush ((GOutputStream*) _tmp3_, NULL, &_inner_error_);
#line 63 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 63 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 63 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 63 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return;
#line 741 "client.c"
	}
	{
		GDataOutputStream* _tmp4_ = NULL;
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_tmp4_ = self->output_stream;
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_output_stream_close ((GOutputStream*) _tmp4_, NULL, &_inner_error_);
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
			if (_inner_error_->domain == G_IO_ERROR) {
#line 753 "client.c"
				goto __catch2_g_io_error;
			}
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
			g_clear_error (&_inner_error_);
#line 65 "/home/stack/Apps/projects/KyRC/src/client.vala"
			return;
#line 762 "client.c"
		}
	}
	goto __finally2;
	__catch2_g_io_error:
	{
		GError* e = NULL;
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
		e = _inner_error_;
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_inner_error_ = NULL;
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
		_g_error_free0 (e);
#line 775 "client.c"
	}
	__finally2:
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 64 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return;
#line 786 "client.c"
	}
}


void client_send_output (Client* self, const gchar* output) {
	GDataOutputStream* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 69 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (output != NULL);
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = self->output_stream;
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = output;
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp2_ = g_strconcat (_tmp1_, "\r\n", NULL);
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp3_ = _tmp2_;
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_data_output_stream_put_string (_tmp0_, _tmp3_, NULL, &_inner_error_);
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (_tmp3_);
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
		g_clear_error (&_inner_error_);
#line 71 "/home/stack/Apps/projects/KyRC/src/client.vala"
		return;
#line 821 "client.c"
	}
}


Client* client_construct (GType object_type) {
	Client * self = NULL;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self = (Client*) g_object_new (object_type, NULL);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return self;
#line 832 "client.c"
}


Client* client_new (void) {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	return client_construct (TYPE_CLIENT);
#line 839 "client.c"
}


static void g_cclosure_user_marshal_VOID__INT_STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__INT_STRING) (gpointer data1, gint arg_1, const char* arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT_STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_return_if_fail (n_param_values == 3);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	if (G_CCLOSURE_SWAP_DATA (closure)) {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data1 = closure->data;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data2 = param_values->data[0].v_pointer;
#line 858 "client.c"
	} else {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data1 = param_values->data[0].v_pointer;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
		data2 = closure->data;
#line 864 "client.c"
	}
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	callback = (GMarshalFunc_VOID__INT_STRING) (marshal_data ? marshal_data : cc->callback);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	callback (data1, g_value_get_int (param_values + 1), g_value_get_string (param_values + 2), data2);
#line 870 "client.c"
}


static void client_class_init (ClientClass * klass) {
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	client_parent_class = g_type_class_peek_parent (klass);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_type_class_add_private (klass, sizeof (ClientPrivate));
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	G_OBJECT_CLASS (klass)->finalize = client_finalize;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	g_signal_new ("new_data", TYPE_CLIENT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT_STRING, G_TYPE_NONE, 2, G_TYPE_INT, G_TYPE_STRING);
#line 883 "client.c"
}


static void client_instance_init (Client * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->priv = CLIENT_GET_PRIVATE (self);
#line 9 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp0_ = g_strdup ("");
#line 9 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->priv->url = _tmp0_;
#line 11 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_tmp1_ = g_strdup ("");
#line 11 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->username = _tmp1_;
#line 12 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self->exit = FALSE;
#line 902 "client.c"
}


static void client_finalize (GObject* obj) {
	Client * self;
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CLIENT, Client);
#line 7 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->input_stream);
#line 8 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_object_unref0 (self->output_stream);
#line 9 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (self->priv->url);
#line 11 "/home/stack/Apps/projects/KyRC/src/client.vala"
	_g_free0 (self->username);
#line 4 "/home/stack/Apps/projects/KyRC/src/client.vala"
	G_OBJECT_CLASS (client_parent_class)->finalize (obj);
#line 920 "client.c"
}


GType client_get_type (void) {
	static volatile gsize client_type_id__volatile = 0;
	if (g_once_init_enter (&client_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ClientClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) client_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Client), 0, (GInstanceInitFunc) client_instance_init, NULL };
		GType client_type_id;
		client_type_id = g_type_register_static (G_TYPE_OBJECT, "Client", &g_define_type_info, 0);
		g_once_init_leave (&client_type_id__volatile, client_type_id);
	}
	return client_type_id__volatile;
}



