/* kyrc.c generated by valac 0.26.2, the Vala compiler
 * generated from kyrc.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * main.c
 * Copyright (C) 2015 Kyle Agronick <agronick@gmail.com>
 * 
 * KyRC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * KyRC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <granite.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <stdio.h>
#include <gio/gio.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define TYPE_SQL_CLIENT (sql_client_get_type ())
#define SQL_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SQL_CLIENT, SqlClient))
#define SQL_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SQL_CLIENT, SqlClientClass))
#define IS_SQL_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SQL_CLIENT))
#define IS_SQL_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SQL_CLIENT))
#define SQL_CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SQL_CLIENT, SqlClientClass))

typedef struct _SqlClient SqlClient;
typedef struct _SqlClientClass SqlClientClass;

#define TYPE_CLIENT (client_get_type ())
#define CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLIENT, Client))
#define CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLIENT, ClientClass))
#define IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLIENT))
#define IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLIENT))
#define CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLIENT, ClientClass))

typedef struct _Client Client;
typedef struct _ClientClass ClientClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ClientPrivate ClientPrivate;
typedef struct _Block2Data Block2Data;

#define SQL_CLIENT_TYPE_SERVER (sql_client_server_get_type ())
#define SQL_CLIENT_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SQL_CLIENT_TYPE_SERVER, SqlClientServer))
#define SQL_CLIENT_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SQL_CLIENT_TYPE_SERVER, SqlClientServerClass))
#define SQL_CLIENT_IS_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SQL_CLIENT_TYPE_SERVER))
#define SQL_CLIENT_IS_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SQL_CLIENT_TYPE_SERVER))
#define SQL_CLIENT_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SQL_CLIENT_TYPE_SERVER, SqlClientServerClass))

typedef struct _SqlClientServer SqlClientServer;
typedef struct _SqlClientServerClass SqlClientServerClass;
typedef struct _SqlClientServerPrivate SqlClientServerPrivate;

#define SQL_CLIENT_TYPE_CHANNEL (sql_client_channel_get_type ())
#define SQL_CLIENT_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannel))
#define SQL_CLIENT_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannelClass))
#define SQL_CLIENT_IS_CHANNEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SQL_CLIENT_TYPE_CHANNEL))
#define SQL_CLIENT_IS_CHANNEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SQL_CLIENT_TYPE_CHANNEL))
#define SQL_CLIENT_CHANNEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SQL_CLIENT_TYPE_CHANNEL, SqlClientChannelClass))

typedef struct _SqlClientChannel SqlClientChannel;
typedef struct _SqlClientChannelClass SqlClientChannelClass;
typedef struct _SqlClientChannelPrivate SqlClientChannelPrivate;
#define _sql_client_channel_unref0(var) ((var == NULL) ? NULL : (var = (sql_client_channel_unref (var), NULL)))

#define TYPE_SERVER_MANAGER (server_manager_get_type ())
#define SERVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SERVER_MANAGER, ServerManager))
#define SERVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SERVER_MANAGER, ServerManagerClass))
#define IS_SERVER_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SERVER_MANAGER))
#define IS_SERVER_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SERVER_MANAGER))
#define SERVER_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SERVER_MANAGER, ServerManagerClass))

typedef struct _ServerManager ServerManager;
typedef struct _ServerManagerClass ServerManagerClass;
typedef struct _Block3Data Block3Data;

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};

struct _MainPrivate {
	GraniteWidgetsDynamicNotebook* tabs;
	GtkWindow* window;
	GtkEntry* input;
	SqlClient* sqlclient;
	GtkPaned* pannel;
	GeeHashMap* outputs;
	GeeHashMap* clients;
	GraniteWidgetsSourceList* servers;
};

struct _Block1Data {
	int _ref_count_;
	Main* self;
	GtkDialog* dialog;
	GtkEntry* server_name;
};

struct _Client {
	GObject parent_instance;
	ClientPrivate * priv;
	GDataInputStream* input_stream;
	GDataOutputStream* output_stream;
	gchar* url;
	gint tab;
	gchar* username;
	gboolean exit;
};

struct _ClientClass {
	GObjectClass parent_class;
};

struct _Block2Data {
	int _ref_count_;
	Main* self;
	GtkTextView* tv;
	GtkScrolledWindow* sw;
	gchar* data;
};

struct _SqlClientServer {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SqlClientServerPrivate * priv;
	gint id;
	gchar* host;
	gint port;
	gchar* nickname;
	gchar* realname;
	gchar* username;
	gchar* password;
	gchar* on_connect;
	gboolean encryption;
	gboolean autoconnect;
	gboolean validate_server;
	GeeArrayList* channels;
};

struct _SqlClientServerClass {
	GTypeClass parent_class;
	void (*finalize) (SqlClientServer *self);
};

struct _SqlClientChannel {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SqlClientChannelPrivate * priv;
	gint id;
	gint server_id;
	gchar* channel;
};

struct _SqlClientChannelClass {
	GTypeClass parent_class;
	void (*finalize) (SqlClientChannel *self);
};

struct _Block3Data {
	int _ref_count_;
	Main* self;
	ServerManager* sm;
};


static gpointer main_parent_class = NULL;
extern gint main_index;
gint main_index = 0;
extern gboolean main_is_locked;
gboolean main_is_locked = FALSE;
extern GeeHashMap* sql_client_servers;

GType main_get_type (void) G_GNUC_CONST;
GType sql_client_get_type (void) G_GNUC_CONST;
GType client_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY
};
SqlClient* sql_client_get_instance (void);
#define MAIN_UI_FILE "src/kyrc.ui"
#define MAIN_UI_FILE_SERVERS "src/server_window.ui"
Main* main_new (void);
Main* main_construct (GType object_type);
gboolean main_slide_panel (Main* self);
static gboolean _main_slide_panel_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void ___lambda5_ (Main* self);
void main_send_text_out (Main* self, const gchar* text);
static void ____lambda5__gtk_entry_activate (GtkEntry* _sender, gpointer self);
void main_refresh_server_list (Main* self);
void main_set_up_add_sever (Main* self, GtkHeaderBar* toolbar);
void main_add_tab (Main* self, const gchar* url);
static void ___lambda11_ (Main* self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda12_ (Block1Data* _data1_);
static void ___lambda12__gtk_entry_activate (GtkEntry* _sender, gpointer self);
static void __lambda13_ (Block1Data* _data1_, gint id);
static void ___lambda13__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static void ____lambda11__granite_widgets_dynamic_notebook_new_tab_requested (GraniteWidgetsDynamicNotebook* _sender, gpointer self);
Client* client_new (void);
Client* client_construct (GType object_type);
void main_add_text (Main* self, gint index, const gchar* data);
static void _main_add_text_client_new_data (Client* _sender, gint index, const gchar* data, gpointer self);
gboolean client_connect_to_server (Client* self, const gchar* location, gint tab_page);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static gboolean __lambda6_ (Block2Data* _data2_);
static gboolean ___lambda6__gsource_func (gpointer self);
static gboolean __lambda7_ (Block2Data* _data2_);
static gboolean ___lambda7__gsource_func (gpointer self);
void client_send_output (Client* self, const gchar* output);
gpointer sql_client_server_ref (gpointer instance);
void sql_client_server_unref (gpointer instance);
GParamSpec* sql_client_param_spec_server (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sql_client_value_set_server (GValue* value, gpointer v_object);
void sql_client_value_take_server (GValue* value, gpointer v_object);
gpointer sql_client_value_get_server (const GValue* value);
GType sql_client_server_get_type (void) G_GNUC_CONST;
gpointer sql_client_channel_ref (gpointer instance);
void sql_client_channel_unref (gpointer instance);
GParamSpec* sql_client_param_spec_channel (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void sql_client_value_set_channel (GValue* value, gpointer v_object);
void sql_client_value_take_channel (GValue* value, gpointer v_object);
gpointer sql_client_value_get_channel (const GValue* value);
GType sql_client_channel_get_type (void) G_GNUC_CONST;
gint main_move_slider_t (Main* self);
static gpointer _main_move_slider_t_gthread_func (gpointer self);
GType server_manager_get_type (void) G_GNUC_CONST;
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
ServerManager* server_manager_new (void);
ServerManager* server_manager_construct (GType object_type);
static gboolean __lambda10_ (Block3Data* _data3_, GdkEventButton* event);
gboolean server_manager_open_window (ServerManager* self, GdkEventButton* event);
static gboolean ___lambda10__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void main_remove_tab (Main* self, gint index);
void client_stop (Client* self);
void main_on_destroy (GtkWidget* window, Main* self);
static gint main_main (gchar** args, int args_length1);
static void main_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 64 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return self ? g_object_ref (self) : NULL;
#line 282 "kyrc.c"
}


static gboolean _main_slide_panel_gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = main_slide_panel ((Main*) self);
#line 78 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 291 "kyrc.c"
}


static void ___lambda5_ (Main* self) {
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkEntry* _tmp2_ = NULL;
#line 84 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->input;
#line 84 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 84 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_send_text_out (self, _tmp1_);
#line 85 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = self->priv->input;
#line 85 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_entry_set_text (_tmp2_, "");
#line 309 "kyrc.c"
}


static void ____lambda5__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	___lambda5_ ((Main*) self);
#line 316 "kyrc.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return _data1_;
#line 325 "kyrc.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 334 "kyrc.c"
		Main* self;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self = _data1_->self;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_data1_->server_name);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_data1_->dialog);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_slice_free (Block1Data, _data1_);
#line 346 "kyrc.c"
	}
}


static void __lambda12_ (Block1Data* _data1_) {
	Main* self;
#line 110 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = _data1_->self;
#line 111 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_dialog_response (_data1_->dialog, (gint) GTK_RESPONSE_ACCEPT);
#line 357 "kyrc.c"
}


static void ___lambda12__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 110 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	__lambda12_ (self);
#line 364 "kyrc.c"
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
#line 1115 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1116 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp0_ = g_strdup (self);
#line 1116 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_result_ = _tmp0_;
#line 1117 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	_tmp1_ = _result_;
#line 1117 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	g_strstrip (_tmp1_);
#line 1118 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	result = _result_;
#line 1118 "/usr/share/vala-0.26/vapi/glib-2.0.vapi"
	return result;
#line 387 "kyrc.c"
}


static void __lambda13_ (Block1Data* _data1_, gint id) {
	Main* self;
	gint _tmp0_ = 0;
#line 115 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = _data1_->self;
#line 116 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = id;
#line 116 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	switch (_tmp0_) {
#line 116 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		case GTK_RESPONSE_ACCEPT:
#line 402 "kyrc.c"
		{
			gchar* name = NULL;
			const gchar* _tmp1_ = NULL;
			gchar* _tmp2_ = NULL;
			const gchar* _tmp3_ = NULL;
			gint _tmp4_ = 0;
			gint _tmp5_ = 0;
#line 118 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp1_ = gtk_entry_get_text (_data1_->server_name);
#line 118 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp2_ = string_strip (_tmp1_);
#line 118 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			name = _tmp2_;
#line 119 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp3_ = name;
#line 119 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp4_ = strlen (_tmp3_);
#line 119 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp5_ = _tmp4_;
#line 119 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			if (_tmp5_ > 2) {
#line 424 "kyrc.c"
				const gchar* _tmp6_ = NULL;
#line 121 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp6_ = name;
#line 121 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				main_add_tab (self, _tmp6_);
#line 122 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				g_signal_emit_by_name (_data1_->dialog, "close");
#line 432 "kyrc.c"
			}
#line 124 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_free0 (name);
#line 124 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			break;
#line 438 "kyrc.c"
		}
#line 116 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		case GTK_RESPONSE_CANCEL:
#line 442 "kyrc.c"
		{
#line 126 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			g_signal_emit_by_name (_data1_->dialog, "close");
#line 127 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			break;
#line 448 "kyrc.c"
		}
		default:
#line 116 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		break;
#line 453 "kyrc.c"
	}
}


static void ___lambda13__gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 115 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	__lambda13_ (self, response_id);
#line 461 "kyrc.c"
}


static void ___lambda11_ (Main* self) {
	Block1Data* _data1_;
	GtkWindow* _tmp0_ = NULL;
	GtkDialog* _tmp1_ = NULL;
	GtkBox* content = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	GtkEntry* _tmp6_ = NULL;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->_ref_count_ = 1;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->self = g_object_ref (self);
#line 103 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->window;
#line 103 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = (GtkDialog*) gtk_dialog_new_with_buttons ("New Connection", _tmp0_, GTK_DIALOG_DESTROY_WITH_PARENT, "Connect", GTK_RESPONSE_ACCEPT, "Cancel", GTK_RESPONSE_CANCEL, NULL);
#line 103 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp1_);
#line 103 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->dialog = _tmp1_;
#line 107 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = (GtkBox*) gtk_dialog_get_content_area (_data1_->dialog);
#line 107 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp2_, gtk_box_get_type ()) ? ((GtkBox*) _tmp2_) : NULL);
#line 107 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	content = _tmp3_;
#line 108 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = (GtkLabel*) gtk_label_new ("Server address");
#line 108 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp4_);
#line 108 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = _tmp4_;
#line 108 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_box_pack_start (content, (GtkWidget*) _tmp5_, FALSE, FALSE, (guint) 5);
#line 108 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (_tmp5_);
#line 109 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = (GtkEntry*) gtk_entry_new ();
#line 109 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp6_);
#line 109 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->server_name = _tmp6_;
#line 110 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_signal_connect_data (_data1_->server_name, "activate", (GCallback) ___lambda12__gtk_entry_activate, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 113 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_box_pack_start (content, (GtkWidget*) _data1_->server_name, FALSE, FALSE, (guint) 5);
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_widget_show_all ((GtkWidget*) _data1_->dialog);
#line 115 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_signal_connect_data (_data1_->dialog, "response", (GCallback) ___lambda13__gtk_dialog_response, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (content);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	block1_data_unref (_data1_);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_ = NULL;
#line 525 "kyrc.c"
}


static void ____lambda11__granite_widgets_dynamic_notebook_new_tab_requested (GraniteWidgetsDynamicNotebook* _sender, gpointer self) {
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	___lambda11_ ((Main*) self);
#line 532 "kyrc.c"
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	GError * _inner_error_ = NULL;
#line 49 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = (Main*) g_object_new (object_type, NULL);
#line 541 "kyrc.c"
	{
		GtkSettings* _tmp0_ = NULL;
		GtkBuilder* builder = NULL;
		GtkBuilder* _tmp1_ = NULL;
		GtkHeaderBar* toolbar = NULL;
		GtkHeaderBar* _tmp2_ = NULL;
		GraniteWidgetsDynamicNotebook* _tmp3_ = NULL;
		GraniteWidgetsDynamicNotebook* _tmp4_ = NULL;
		GObject* _tmp5_ = NULL;
		GtkWindow* _tmp6_ = NULL;
		GtkBox* nb_wrapper = NULL;
		GObject* _tmp7_ = NULL;
		GtkBox* _tmp8_ = NULL;
		GtkBox* _tmp9_ = NULL;
		GraniteWidgetsDynamicNotebook* _tmp10_ = NULL;
		GObject* _tmp11_ = NULL;
		GtkPaned* _tmp12_ = NULL;
		GtkBox* server_list_container = NULL;
		GObject* _tmp13_ = NULL;
		GtkBox* _tmp14_ = NULL;
		GtkBox* _tmp15_ = NULL;
		GraniteWidgetsSourceList* _tmp16_ = NULL;
		GtkImage* icon = NULL;
		GtkImage* _tmp17_ = NULL;
		GtkButton* select_channel = NULL;
		GtkButton* _tmp18_ = NULL;
		GtkButton* _tmp19_ = NULL;
		GtkImage* _tmp20_ = NULL;
		GtkButton* _tmp21_ = NULL;
		GtkHeaderBar* _tmp22_ = NULL;
		GtkButton* _tmp23_ = NULL;
		GtkButton* _tmp24_ = NULL;
		GtkPaned* _tmp25_ = NULL;
		GObject* _tmp26_ = NULL;
		GtkEntry* _tmp27_ = NULL;
		GtkEntry* _tmp28_ = NULL;
		GtkHeaderBar* _tmp29_ = NULL;
		GtkHeaderBar* _tmp30_ = NULL;
		GtkHeaderBar* _tmp31_ = NULL;
		GtkHeaderBar* _tmp32_ = NULL;
		GtkWindow* _tmp33_ = NULL;
		GtkHeaderBar* _tmp34_ = NULL;
		GtkWindow* _tmp35_ = NULL;
		GraniteWidgetsDynamicNotebook* _tmp36_ = NULL;
#line 54 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp0_ = gtk_settings_get_default ();
#line 54 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_set ((GObject*) _tmp0_, "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 56 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp1_ = gtk_builder_new ();
#line 56 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		builder = _tmp1_;
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_builder_add_from_file (builder, MAIN_UI_FILE, &_inner_error_);
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_object_unref0 (builder);
#line 600 "kyrc.c"
			goto __catch0_g_error;
		}
#line 58 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_builder_connect_signals (builder, self);
#line 60 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp2_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 60 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_ref_sink (_tmp2_);
#line 60 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		toolbar = _tmp2_;
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp3_ = granite_widgets_dynamic_notebook_new ();
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_ref_sink (_tmp3_);
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->tabs);
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->tabs = _tmp3_;
#line 62 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp4_ = self->priv->tabs;
#line 62 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		granite_widgets_dynamic_notebook_set_allow_drag (_tmp4_, TRUE);
#line 64 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp5_ = gtk_builder_get_object (builder, "window");
#line 64 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp5_) : NULL);
#line 64 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->window);
#line 64 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->window = _tmp6_;
#line 65 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp7_ = gtk_builder_get_object (builder, "notebook_wrapper");
#line 65 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, gtk_box_get_type ()) ? ((GtkBox*) _tmp7_) : NULL);
#line 65 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		nb_wrapper = _tmp8_;
#line 66 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp9_ = nb_wrapper;
#line 66 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp10_ = self->priv->tabs;
#line 66 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_box_pack_start (_tmp9_, (GtkWidget*) _tmp10_, TRUE, TRUE, (guint) 1);
#line 69 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp11_ = gtk_builder_get_object (builder, "pannel");
#line 69 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp12_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp11_, gtk_paned_get_type ()) ? ((GtkPaned*) _tmp11_) : NULL);
#line 69 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->pannel);
#line 69 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->pannel = _tmp12_;
#line 70 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp13_ = gtk_builder_get_object (builder, "server_list_container");
#line 70 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp14_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, gtk_box_get_type ()) ? ((GtkBox*) _tmp13_) : NULL);
#line 70 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		server_list_container = _tmp14_;
#line 71 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp15_ = server_list_container;
#line 71 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp16_ = self->priv->servers;
#line 71 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_box_pack_start (_tmp15_, (GtkWidget*) _tmp16_, TRUE, TRUE, (guint) 0);
#line 73 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp17_ = (GtkImage*) gtk_image_new_from_file ("src/assets/server_run.png");
#line 73 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_ref_sink (_tmp17_);
#line 73 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		icon = _tmp17_;
#line 74 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp18_ = (GtkButton*) gtk_button_new ();
#line 74 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_ref_sink (_tmp18_);
#line 74 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		select_channel = _tmp18_;
#line 75 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp19_ = select_channel;
#line 75 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp20_ = icon;
#line 75 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_button_set_image (_tmp19_, (GtkWidget*) _tmp20_);
#line 76 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp21_ = select_channel;
#line 76 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_widget_set_tooltip_text ((GtkWidget*) _tmp21_, "Open server/channel view");
#line 77 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp22_ = toolbar;
#line 77 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp23_ = select_channel;
#line 77 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_header_bar_pack_start (_tmp22_, (GtkWidget*) _tmp23_);
#line 78 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp24_ = select_channel;
#line 78 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_signal_connect_object ((GtkWidget*) _tmp24_, "button-release-event", (GCallback) _main_slide_panel_gtk_widget_button_release_event, self, 0);
#line 79 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp25_ = self->priv->pannel;
#line 79 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_paned_set_position (_tmp25_, 1);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp26_ = gtk_builder_get_object (builder, "input");
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp27_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp26_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp26_) : NULL);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->input);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->input = _tmp27_;
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp28_ = self->priv->input;
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_signal_connect_object (_tmp28_, "activate", (GCallback) ____lambda5__gtk_entry_activate, self, 0);
#line 88 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		main_refresh_server_list (self);
#line 90 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp29_ = toolbar;
#line 90 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		main_set_up_add_sever (self, _tmp29_);
#line 92 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp30_ = toolbar;
#line 92 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_header_bar_set_title (_tmp30_, "Kyrc");
#line 93 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp31_ = toolbar;
#line 93 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_widget_show_all ((GtkWidget*) _tmp31_);
#line 95 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp32_ = toolbar;
#line 95 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_header_bar_set_show_close_button (_tmp32_, TRUE);
#line 96 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp33_ = self->priv->window;
#line 96 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp34_ = toolbar;
#line 96 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_window_set_titlebar (_tmp33_, (GtkWidget*) _tmp34_);
#line 98 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp35_ = self->priv->window;
#line 98 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_widget_show_all ((GtkWidget*) _tmp35_);
#line 100 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		main_add_tab (self, "irc.freenode.net");
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp36_ = self->priv->tabs;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_signal_connect_object (_tmp36_, "new-tab-requested", (GCallback) ____lambda11__granite_widgets_dynamic_notebook_new_tab_requested, self, 0);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (select_channel);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (icon);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (server_list_container);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (nb_wrapper);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (toolbar);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (builder);
#line 757 "kyrc.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp37_ = NULL;
		GError* _tmp38_ = NULL;
		const gchar* _tmp39_ = NULL;
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		e = _inner_error_;
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_inner_error_ = NULL;
#line 133 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp37_ = stderr;
#line 133 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp38_ = e;
#line 133 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp39_ = _tmp38_->message;
#line 133 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		fprintf (_tmp37_, "Could not load UI: %s\n", _tmp39_);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_error_free0 (e);
#line 780 "kyrc.c"
	}
	__finally0:
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_clear_error (&_inner_error_);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		return NULL;
#line 791 "kyrc.c"
	}
#line 49 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return self;
#line 795 "kyrc.c"
}


Main* main_new (void) {
#line 49 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return main_construct (TYPE_MAIN);
#line 802 "kyrc.c"
}


static void _main_add_text_client_new_data (Client* _sender, gint index, const gchar* data, gpointer self) {
#line 162 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_add_text ((Main*) self, index, data);
#line 809 "kyrc.c"
}


void main_add_tab (Main* self, const gchar* url) {
	GtkLabel* title = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkTextView* output = NULL;
	GtkTextView* _tmp2_ = NULL;
	GtkScrolledWindow* scrolled = NULL;
	GtkScrolledWindow* _tmp3_ = NULL;
	GraniteWidgetsTab* tab = NULL;
	GraniteWidgetsTab* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GraniteWidgetsDynamicNotebook* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	GeeHashMap* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	GraniteWidgetsDynamicNotebook* _tmp10_ = NULL;
	Client* client = NULL;
	Client* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	GeeHashMap* _tmp13_ = NULL;
	gint _tmp14_ = 0;
	const gchar* _tmp15_ = NULL;
	gint _tmp16_ = 0;
	gint _tmp17_ = 0;
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (url != NULL);
#line 141 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = url;
#line 141 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 141 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp1_);
#line 141 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	title = _tmp1_;
#line 142 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = (GtkTextView*) gtk_text_view_new ();
#line 142 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp2_);
#line 142 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	output = _tmp2_;
#line 143 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 143 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp3_);
#line 143 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	scrolled = _tmp3_;
#line 144 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_container_add ((GtkContainer*) scrolled, (GtkWidget*) output);
#line 145 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_text_view_set_editable (output, FALSE);
#line 146 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_text_view_set_wrap_mode (output, GTK_WRAP_WORD);
#line 148 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = granite_widgets_tab_new ("", NULL, NULL);
#line 148 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp4_);
#line 148 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	tab = _tmp4_;
#line 149 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = url;
#line 149 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	granite_widgets_tab_set_label (tab, _tmp5_);
#line 151 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	granite_widgets_tab_set_page (tab, (GtkWidget*) scrolled);
#line 152 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = self->priv->tabs;
#line 152 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp7_ = main_index;
#line 152 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	granite_widgets_dynamic_notebook_insert_tab (_tmp6_, tab, _tmp7_);
#line 154 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp8_ = self->priv->outputs;
#line 154 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp9_ = main_index;
#line 154 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp8_, (gpointer) ((gintptr) _tmp9_), output);
#line 156 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp10_ = self->priv->tabs;
#line 156 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp10_);
#line 158 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp11_ = client_new ();
#line 158 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client = _tmp11_;
#line 159 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp12_ = g_strdup ("kyle123456");
#line 159 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_free0 (client->username);
#line 159 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client->username = _tmp12_;
#line 160 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp13_ = self->priv->clients;
#line 160 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp14_ = main_index;
#line 160 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp13_, (gpointer) ((gintptr) _tmp14_), client);
#line 162 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_signal_connect_object (client, "new-data", (GCallback) _main_add_text_client_new_data, self, 0);
#line 163 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp15_ = url;
#line 163 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp16_ = main_index;
#line 163 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client_connect_to_server (client, _tmp15_, _tmp16_);
#line 165 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp17_ = main_index;
#line 165 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_index = _tmp17_ + 1;
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (client);
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (tab);
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (scrolled);
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (output);
#line 139 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (title);
#line 933 "kyrc.c"
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_atomic_int_inc (&_data2_->_ref_count_);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return _data2_;
#line 942 "kyrc.c"
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
#line 951 "kyrc.c"
		Main* self;
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self = _data2_->self;
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_data2_->sw);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_data2_->tv);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_free0 (_data2_->data);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_slice_free (Block2Data, _data2_);
#line 965 "kyrc.c"
	}
}


static gboolean __lambda6_ (Block2Data* _data2_) {
	Main* self;
	gboolean result = FALSE;
	GtkTextIter outiter = {0};
	GtkTextView* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkTextBuffer* _tmp2_ = NULL;
	GtkTextIter _tmp3_ = {0};
	GtkTextView* _tmp4_ = NULL;
	GtkTextBuffer* _tmp5_ = NULL;
	GtkTextBuffer* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gint _tmp10_ = 0;
	GtkAdjustment* adj = NULL;
	GtkScrolledWindow* _tmp11_ = NULL;
	GtkAdjustment* _tmp12_ = NULL;
	GtkAdjustment* _tmp13_ = NULL;
	gdouble _tmp14_ = 0.0;
	gdouble _tmp15_ = 0.0;
#line 177 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = _data2_->self;
#line 178 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_is_locked = TRUE;
#line 180 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = _data2_->tv;
#line 180 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gtk_text_view_get_buffer (_tmp0_);
#line 180 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = _tmp1_;
#line 180 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_text_buffer_get_end_iter (_tmp2_, &_tmp3_);
#line 180 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	outiter = _tmp3_;
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = _data2_->tv;
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = gtk_text_view_get_buffer (_tmp4_);
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = _tmp5_;
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp7_ = _data2_->data;
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp8_ = _data2_->data;
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp9_ = strlen (_tmp8_);
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp10_ = _tmp9_;
#line 181 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_text_buffer_insert (_tmp6_, &outiter, _tmp7_, _tmp10_);
#line 182 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp11_ = _data2_->sw;
#line 182 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp12_ = gtk_scrolled_window_get_vadjustment (_tmp11_);
#line 182 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp13_ = _g_object_ref0 (_tmp12_);
#line 182 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	adj = _tmp13_;
#line 183 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp14_ = gtk_adjustment_get_upper (adj);
#line 183 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp15_ = gtk_adjustment_get_page_size (adj);
#line 183 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_adjustment_set_value (adj, _tmp14_ - _tmp15_);
#line 184 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_is_locked = FALSE;
#line 185 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = FALSE;
#line 185 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (adj);
#line 185 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1043 "kyrc.c"
}


static gboolean ___lambda6__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda6_ (self);
#line 177 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1052 "kyrc.c"
}


static gboolean __lambda7_ (Block2Data* _data2_) {
	Main* self;
	gboolean result = FALSE;
	GtkAdjustment* adj = NULL;
	GtkScrolledWindow* _tmp0_ = NULL;
	GtkAdjustment* _tmp1_ = NULL;
	GtkAdjustment* _tmp2_ = NULL;
	gdouble _tmp3_ = 0.0;
	gdouble _tmp4_ = 0.0;
	GtkScrolledWindow* _tmp5_ = NULL;
#line 191 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = _data2_->self;
#line 192 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = _data2_->sw;
#line 192 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gtk_scrolled_window_get_vadjustment (_tmp0_);
#line 192 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = _g_object_ref0 (_tmp1_);
#line 192 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	adj = _tmp2_;
#line 193 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = gtk_adjustment_get_upper (adj);
#line 193 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = gtk_adjustment_get_page_size (adj);
#line 193 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_adjustment_set_value (adj, _tmp3_ - _tmp4_);
#line 194 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = _data2_->sw;
#line 194 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_scrolled_window_set_vadjustment (_tmp5_, adj);
#line 195 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = FALSE;
#line 195 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (adj);
#line 195 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1092 "kyrc.c"
}


static gboolean ___lambda7__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda7_ (self);
#line 191 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1101 "kyrc.c"
}


void main_add_text (Main* self, gint index, const gchar* data) {
	Block2Data* _data2_;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gpointer _tmp4_ = NULL;
	GtkTextView* _tmp5_ = NULL;
	GtkContainer* _tmp6_ = NULL;
	GtkScrolledWindow* _tmp7_ = NULL;
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (data != NULL);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_ = g_slice_new0 (Block2Data);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_->_ref_count_ = 1;
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_->self = g_object_ref (self);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = data;
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_free0 (_data2_->data);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_->data = _tmp1_;
#line 171 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = self->priv->outputs;
#line 171 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = index;
#line 171 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, (gpointer) ((gintptr) _tmp3_));
#line 171 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_->tv = (GtkTextView*) _tmp4_;
#line 172 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = _data2_->tv;
#line 172 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = (GtkContainer*) gtk_widget_get_parent ((GtkWidget*) _tmp5_);
#line 172 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp7_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp6_, gtk_scrolled_window_get_type (), GtkScrolledWindow));
#line 172 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_->sw = _tmp7_;
#line 173 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	while (TRUE) {
#line 1151 "kyrc.c"
		gboolean _tmp8_ = FALSE;
#line 173 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp8_ = main_is_locked;
#line 173 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		if (!_tmp8_) {
#line 173 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			break;
#line 1159 "kyrc.c"
		}
#line 175 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_usleep ((gulong) 111);
#line 1163 "kyrc.c"
	}
#line 177 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda6__gsource_func, block2_data_ref (_data2_), block2_data_unref);
#line 189 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_usleep ((gulong) 5000);
#line 191 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda7__gsource_func, block2_data_ref (_data2_), block2_data_unref);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	block2_data_unref (_data2_);
#line 169 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data2_ = NULL;
#line 1175 "kyrc.c"
}


void main_send_text_out (Main* self, const gchar* text) {
	GraniteWidgetsTab* current = NULL;
	GraniteWidgetsDynamicNotebook* _tmp0_ = NULL;
	GraniteWidgetsTab* _tmp1_ = NULL;
	GraniteWidgetsTab* _tmp2_ = NULL;
	GraniteWidgetsTab* _tmp3_ = NULL;
#line 200 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 200 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (text != NULL);
#line 202 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->tabs;
#line 202 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = granite_widgets_dynamic_notebook_get_current (_tmp0_);
#line 202 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = _tmp1_;
#line 202 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 202 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	current = _tmp3_;
#line 1199 "kyrc.c"
	{
		GeeIterator* _client_it = NULL;
		GeeHashMap* _tmp4_ = NULL;
		GeeSet* _tmp5_ = NULL;
		GeeSet* _tmp6_ = NULL;
		GeeSet* _tmp7_ = NULL;
		GeeIterator* _tmp8_ = NULL;
		GeeIterator* _tmp9_ = NULL;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp4_ = self->priv->clients;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp5_ = gee_abstract_map_get_entries ((GeeMap*) _tmp4_);
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp6_ = _tmp5_;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp7_ = _tmp6_;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp8_ = gee_iterable_iterator ((GeeIterable*) _tmp7_);
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp9_ = _tmp8_;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_tmp7_);
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_client_it = _tmp9_;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		while (TRUE) {
#line 1226 "kyrc.c"
			GeeIterator* _tmp10_ = NULL;
			gboolean _tmp11_ = FALSE;
			GeeMapEntry* client = NULL;
			GeeIterator* _tmp12_ = NULL;
			gpointer _tmp13_ = NULL;
			GraniteWidgetsTab* _tmp14_ = NULL;
			const gchar* _tmp15_ = NULL;
			const gchar* _tmp16_ = NULL;
			GeeMapEntry* _tmp17_ = NULL;
			gconstpointer _tmp18_ = NULL;
			Client* _tmp19_ = NULL;
			const gchar* _tmp20_ = NULL;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp10_ = _client_it;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp11_ = gee_iterator_next (_tmp10_);
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			if (!_tmp11_) {
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				break;
#line 1247 "kyrc.c"
			}
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp12_ = _client_it;
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp13_ = gee_iterator_get (_tmp12_);
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			client = (GeeMapEntry*) _tmp13_;
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp14_ = current;
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp15_ = granite_widgets_tab_get_label (_tmp14_);
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp16_ = _tmp15_;
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp17_ = client;
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp18_ = gee_map_entry_get_value (_tmp17_);
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp19_ = _tmp18_;
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp20_ = ((Client*) _tmp19_)->url;
#line 205 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			if (g_strcmp0 (_tmp16_, _tmp20_) == 0) {
#line 1271 "kyrc.c"
				gint page = 0;
				GeeMapEntry* _tmp21_ = NULL;
				gconstpointer _tmp22_ = NULL;
				Client* _tmp23_ = NULL;
				gint _tmp24_ = 0;
				GeeHashMap* _tmp25_ = NULL;
				gint _tmp26_ = 0;
				gpointer _tmp27_ = NULL;
				Client* _tmp28_ = NULL;
				const gchar* _tmp29_ = NULL;
				gint _tmp30_ = 0;
				GeeHashMap* _tmp31_ = NULL;
				gint _tmp32_ = 0;
				gpointer _tmp33_ = NULL;
				Client* _tmp34_ = NULL;
				const gchar* _tmp35_ = NULL;
				gchar* _tmp36_ = NULL;
				gchar* _tmp37_ = NULL;
				const gchar* _tmp38_ = NULL;
				gchar* _tmp39_ = NULL;
				gchar* _tmp40_ = NULL;
#line 207 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp21_ = client;
#line 207 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp22_ = gee_map_entry_get_value (_tmp21_);
#line 207 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp23_ = _tmp22_;
#line 207 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp24_ = ((Client*) _tmp23_)->tab;
#line 207 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				page = _tmp24_;
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp25_ = self->priv->clients;
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp26_ = page;
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp27_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp25_, (gpointer) ((gintptr) _tmp26_));
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp28_ = (Client*) _tmp27_;
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp29_ = text;
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				client_send_output (_tmp28_, _tmp29_);
#line 208 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_object_unref0 (_tmp28_);
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp30_ = page;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp31_ = self->priv->clients;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp32_ = page;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp33_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp31_, (gpointer) ((gintptr) _tmp32_));
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp34_ = (Client*) _tmp33_;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp35_ = _tmp34_->username;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp36_ = g_strconcat (_tmp35_, ": ", NULL);
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp37_ = _tmp36_;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp38_ = text;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp39_ = g_strconcat (_tmp37_, _tmp38_, NULL);
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp40_ = _tmp39_;
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				main_add_text (self, _tmp30_, _tmp40_);
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_free0 (_tmp40_);
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_free0 (_tmp37_);
#line 209 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_object_unref0 (_tmp34_);
#line 210 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_object_unref0 (client);
#line 210 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_object_unref0 (_client_it);
#line 210 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_object_unref0 (current);
#line 210 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				return;
#line 1355 "kyrc.c"
			}
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_object_unref0 (client);
#line 1359 "kyrc.c"
		}
#line 203 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_client_it);
#line 1363 "kyrc.c"
	}
#line 200 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (current);
#line 1367 "kyrc.c"
}


void main_refresh_server_list (Main* self) {
	GraniteWidgetsSourceListExpandableItem* root = NULL;
	GraniteWidgetsSourceList* _tmp0_ = NULL;
	GraniteWidgetsSourceListExpandableItem* _tmp1_ = NULL;
	GraniteWidgetsSourceListExpandableItem* _tmp2_ = NULL;
	GraniteWidgetsSourceListExpandableItem* _tmp3_ = NULL;
#line 215 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 217 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->servers;
#line 217 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = granite_widgets_source_list_get_root (_tmp0_);
#line 217 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = _tmp1_;
#line 217 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = _g_object_ref0 (_tmp2_);
#line 217 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	root = _tmp3_;
#line 1389 "kyrc.c"
	{
		GeeIterator* _svr_it = NULL;
		SqlClient* _tmp4_ = NULL;
		GeeHashMap* _tmp5_ = NULL;
		GeeSet* _tmp6_ = NULL;
		GeeSet* _tmp7_ = NULL;
		GeeSet* _tmp8_ = NULL;
		GeeIterator* _tmp9_ = NULL;
		GeeIterator* _tmp10_ = NULL;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp4_ = self->priv->sqlclient;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp5_ = sql_client_servers;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp6_ = gee_abstract_map_get_entries ((GeeMap*) _tmp5_);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp7_ = _tmp6_;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp8_ = _tmp7_;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp9_ = gee_iterable_iterator ((GeeIterable*) _tmp8_);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp10_ = _tmp9_;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_tmp8_);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_svr_it = _tmp10_;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		while (TRUE) {
#line 1419 "kyrc.c"
			GeeIterator* _tmp11_ = NULL;
			gboolean _tmp12_ = FALSE;
			GeeMapEntry* svr = NULL;
			GeeIterator* _tmp13_ = NULL;
			gpointer _tmp14_ = NULL;
			GraniteWidgetsSourceListExpandableItem* s = NULL;
			GeeMapEntry* _tmp15_ = NULL;
			gconstpointer _tmp16_ = NULL;
			SqlClientServer* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			GraniteWidgetsSourceListExpandableItem* _tmp19_ = NULL;
			GraniteWidgetsSourceListExpandableItem* _tmp20_ = NULL;
			GraniteWidgetsSourceListExpandableItem* _tmp21_ = NULL;
			GraniteWidgetsSourceListItem* chn = NULL;
			GeeMapEntry* _tmp22_ = NULL;
			gconstpointer _tmp23_ = NULL;
			SqlClientServer* _tmp24_ = NULL;
			const gchar* _tmp25_ = NULL;
			GraniteWidgetsSourceListItem* _tmp26_ = NULL;
			GraniteWidgetsSourceListExpandableItem* _tmp27_ = NULL;
			GraniteWidgetsSourceListItem* _tmp28_ = NULL;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp11_ = _svr_it;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp12_ = gee_iterator_next (_tmp11_);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			if (!_tmp12_) {
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				break;
#line 1449 "kyrc.c"
			}
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp13_ = _svr_it;
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp14_ = gee_iterator_get (_tmp13_);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			svr = (GeeMapEntry*) _tmp14_;
#line 220 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp15_ = svr;
#line 220 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp16_ = gee_map_entry_get_value (_tmp15_);
#line 220 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp17_ = _tmp16_;
#line 220 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp18_ = ((SqlClientServer*) _tmp17_)->host;
#line 220 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp19_ = granite_widgets_source_list_expandable_item_new (_tmp18_);
#line 220 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			s = _tmp19_;
#line 221 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp20_ = root;
#line 221 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp21_ = s;
#line 221 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			granite_widgets_source_list_expandable_item_add (_tmp20_, (GraniteWidgetsSourceListItem*) _tmp21_);
#line 222 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp22_ = svr;
#line 222 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp23_ = gee_map_entry_get_value (_tmp22_);
#line 222 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp24_ = _tmp23_;
#line 222 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp25_ = ((SqlClientServer*) _tmp24_)->host;
#line 222 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp26_ = granite_widgets_source_list_item_new (_tmp25_);
#line 222 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			chn = _tmp26_;
#line 223 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp27_ = s;
#line 223 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp28_ = chn;
#line 223 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			granite_widgets_source_list_expandable_item_add (_tmp27_, _tmp28_);
#line 1493 "kyrc.c"
			{
				GeeArrayList* _c_list = NULL;
				GeeMapEntry* _tmp29_ = NULL;
				gconstpointer _tmp30_ = NULL;
				SqlClientServer* _tmp31_ = NULL;
				GeeArrayList* _tmp32_ = NULL;
				GeeArrayList* _tmp33_ = NULL;
				gint _c_size = 0;
				GeeArrayList* _tmp34_ = NULL;
				gint _tmp35_ = 0;
				gint _tmp36_ = 0;
				gint _c_index = 0;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp29_ = svr;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp30_ = gee_map_entry_get_value (_tmp29_);
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp31_ = _tmp30_;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp32_ = ((SqlClientServer*) _tmp31_)->channels;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp33_ = _g_object_ref0 (_tmp32_);
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_c_list = _tmp33_;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp34_ = _c_list;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp35_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp34_);
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp36_ = _tmp35_;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_c_size = _tmp36_;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_c_index = -1;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				while (TRUE) {
#line 1530 "kyrc.c"
					gint _tmp37_ = 0;
					gint _tmp38_ = 0;
					gint _tmp39_ = 0;
					SqlClientChannel* c = NULL;
					GeeArrayList* _tmp40_ = NULL;
					gint _tmp41_ = 0;
					gpointer _tmp42_ = NULL;
					SqlClientChannel* _tmp43_ = NULL;
					const gchar* _tmp44_ = NULL;
					GraniteWidgetsSourceListItem* _tmp45_ = NULL;
					GraniteWidgetsSourceListExpandableItem* _tmp46_ = NULL;
					GraniteWidgetsSourceListItem* _tmp47_ = NULL;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp37_ = _c_index;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_c_index = _tmp37_ + 1;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp38_ = _c_index;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp39_ = _c_size;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					if (!(_tmp38_ < _tmp39_)) {
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
						break;
#line 1555 "kyrc.c"
					}
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp40_ = _c_list;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp41_ = _c_index;
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp42_ = gee_abstract_list_get ((GeeAbstractList*) _tmp40_, _tmp41_);
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					c = (SqlClientChannel*) _tmp42_;
#line 226 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp43_ = c;
#line 226 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp44_ = _tmp43_->channel;
#line 226 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp45_ = granite_widgets_source_list_item_new (_tmp44_);
#line 226 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_g_object_unref0 (chn);
#line 226 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					chn = _tmp45_;
#line 227 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp46_ = s;
#line 227 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp47_ = chn;
#line 227 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					granite_widgets_source_list_expandable_item_add (_tmp46_, _tmp47_);
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_sql_client_channel_unref0 (c);
#line 1583 "kyrc.c"
				}
#line 224 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_g_object_unref0 (_c_list);
#line 1587 "kyrc.c"
			}
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_object_unref0 (chn);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_object_unref0 (s);
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_object_unref0 (svr);
#line 1595 "kyrc.c"
		}
#line 218 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_svr_it);
#line 1599 "kyrc.c"
	}
#line 215 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (root);
#line 1603 "kyrc.c"
}


static gpointer _main_move_slider_t_gthread_func (gpointer self) {
	gpointer result;
	result = (gpointer) ((gintptr) main_move_slider_t ((Main*) self));
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_unref (self);
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1614 "kyrc.c"
}


gboolean main_slide_panel (Main* self) {
	gboolean result = FALSE;
	GError * _inner_error_ = NULL;
#line 232 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_thread_create (_main_move_slider_t_gthread_func, g_object_ref (self), TRUE, &_inner_error_);
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_clear_error (&_inner_error_);
#line 234 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		return FALSE;
#line 1633 "kyrc.c"
	}
#line 235 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = FALSE;
#line 235 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1639 "kyrc.c"
}


gint main_move_slider_t (Main* self) {
	gint result = 0;
	gint add = 0;
	gint end = 0;
	gboolean opening = FALSE;
	GtkPaned* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
#line 238 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 242 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->pannel;
#line 242 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gtk_paned_get_position (_tmp0_);
#line 242 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = _tmp1_;
#line 242 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (_tmp2_ < 10) {
#line 244 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		opening = TRUE;
#line 245 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		add = 1;
#line 246 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		end = 150;
#line 1667 "kyrc.c"
	} else {
#line 248 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		opening = FALSE;
#line 249 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		add = -1;
#line 250 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		end = 0;
#line 1675 "kyrc.c"
	}
	{
		gint i = 0;
		GtkPaned* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp3_ = self->priv->pannel;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp4_ = gtk_paned_get_position (_tmp3_);
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp5_ = _tmp4_;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		i = _tmp5_;
#line 1690 "kyrc.c"
		{
			gboolean _tmp6_ = FALSE;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_tmp6_ = TRUE;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			while (TRUE) {
#line 1697 "kyrc.c"
				gboolean _tmp9_ = FALSE;
				gboolean _tmp10_ = FALSE;
				GtkPaned* _tmp15_ = NULL;
				gint _tmp16_ = 0;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				if (!_tmp6_) {
#line 1704 "kyrc.c"
					gint _tmp7_ = 0;
					gint _tmp8_ = 0;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp7_ = i;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp8_ = add;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					i = _tmp7_ + _tmp8_;
#line 1713 "kyrc.c"
				}
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp6_ = FALSE;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp10_ = opening;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				if (_tmp10_) {
#line 1721 "kyrc.c"
					gint _tmp11_ = 0;
					gint _tmp12_ = 0;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp11_ = i;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp12_ = end;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp9_ = _tmp11_ < _tmp12_;
#line 1730 "kyrc.c"
				} else {
					gint _tmp13_ = 0;
					gint _tmp14_ = 0;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp13_ = end;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp14_ = i;
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					_tmp9_ = _tmp13_ < _tmp14_;
#line 1740 "kyrc.c"
				}
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				if (!_tmp9_) {
#line 252 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
					break;
#line 1746 "kyrc.c"
				}
#line 254 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp15_ = self->priv->pannel;
#line 254 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				_tmp16_ = i;
#line 254 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				gtk_paned_set_position (_tmp15_, _tmp16_);
#line 255 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
				g_usleep ((gulong) 3600);
#line 1756 "kyrc.c"
			}
		}
	}
#line 257 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = 0;
#line 257 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1764 "kyrc.c"
}


static Block3Data* block3_data_ref (Block3Data* _data3_) {
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return _data3_;
#line 1773 "kyrc.c"
}


static void block3_data_unref (void * _userdata_) {
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 1782 "kyrc.c"
		Main* self;
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self = _data3_->self;
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_data3_->sm);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_slice_free (Block3Data, _data3_);
#line 1792 "kyrc.c"
	}
}


static gboolean __lambda10_ (Block3Data* _data3_, GdkEventButton* event) {
	Main* self;
	gboolean result = FALSE;
	GdkEventButton* _tmp0_ = NULL;
#line 266 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = _data3_->self;
#line 266 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_val_if_fail (event != NULL, FALSE);
#line 267 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = event;
#line 267 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	server_manager_open_window (_data3_->sm, _tmp0_);
#line 268 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_refresh_server_list (self);
#line 269 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = FALSE;
#line 269 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1815 "kyrc.c"
}


static gboolean ___lambda10__gtk_widget_button_release_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = __lambda10_ (self, event);
#line 266 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1824 "kyrc.c"
}


void main_set_up_add_sever (Main* self, GtkHeaderBar* toolbar) {
	Block3Data* _data3_;
	GtkButton* add_server_button = NULL;
	GtkButton* _tmp0_ = NULL;
	ServerManager* _tmp1_ = NULL;
	GtkHeaderBar* _tmp2_ = NULL;
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (toolbar != NULL);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data3_->_ref_count_ = 1;
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data3_->self = g_object_ref (self);
#line 262 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = (GtkButton*) gtk_button_new_from_icon_name ("list-add-symbolic", GTK_ICON_SIZE_LARGE_TOOLBAR);
#line 262 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp0_);
#line 262 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	add_server_button = _tmp0_;
#line 263 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_widget_set_tooltip_text ((GtkWidget*) add_server_button, "Add new server");
#line 265 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = server_manager_new ();
#line 265 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data3_->sm = _tmp1_;
#line 266 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_signal_connect_data ((GtkWidget*) add_server_button, "button-release-event", (GCallback) ___lambda10__gtk_widget_button_release_event, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
#line 272 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = toolbar;
#line 272 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_header_bar_pack_start (_tmp2_, (GtkWidget*) add_server_button);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (add_server_button);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	block3_data_unref (_data3_);
#line 260 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data3_ = NULL;
#line 1868 "kyrc.c"
}


static void main_remove_tab (Main* self, gint index) {
	GraniteWidgetsDynamicNotebook* _tmp0_ = NULL;
	GraniteWidgetsDynamicNotebook* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GraniteWidgetsTab* _tmp3_ = NULL;
	GraniteWidgetsTab* _tmp4_ = NULL;
	GeeHashMap* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gpointer _tmp7_ = NULL;
	Client* _tmp8_ = NULL;
	GeeHashMap* _tmp9_ = NULL;
	gint _tmp10_ = 0;
	GeeHashMap* _tmp11_ = NULL;
	gint _tmp12_ = 0;
#line 275 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->tabs;
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = self->priv->tabs;
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = index;
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = granite_widgets_dynamic_notebook_get_tab_by_index (_tmp1_, _tmp2_);
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = _tmp3_;
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	granite_widgets_dynamic_notebook_remove_tab (_tmp0_, _tmp4_);
#line 277 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (_tmp4_);
#line 278 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = self->priv->clients;
#line 278 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = index;
#line 278 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp7_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp5_, (gpointer) ((gintptr) _tmp6_));
#line 278 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp8_ = (Client*) _tmp7_;
#line 278 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client_stop (_tmp8_);
#line 278 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (_tmp8_);
#line 279 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp9_ = self->priv->clients;
#line 279 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp10_ = index;
#line 279 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp9_, (gpointer) ((gintptr) _tmp10_), NULL);
#line 280 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp11_ = self->priv->outputs;
#line 280 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp12_ = index;
#line 280 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gee_abstract_map_unset ((GeeAbstractMap*) _tmp11_, (gpointer) ((gintptr) _tmp12_), NULL);
#line 1926 "kyrc.c"
}


void main_on_destroy (GtkWidget* window, Main* self) {
#line 284 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 284 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (window != NULL);
#line 286 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_main_quit ();
#line 1937 "kyrc.c"
}


static gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	Main* app = NULL;
	Main* _tmp0_ = NULL;
#line 291 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_init (&args_length1, &args);
#line 292 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = main_new ();
#line 292 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	app = _tmp0_;
#line 294 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_main ();
#line 296 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = 0;
#line 296 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (app);
#line 296 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 1959 "kyrc.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 289 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return main_main (argv, argc);
#line 1969 "kyrc.c"
}


static void main_class_init (MainClass * klass) {
#line 25 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_parent_class = g_type_class_peek_parent (klass);
#line 25 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_type_class_add_private (klass, sizeof (MainPrivate));
#line 25 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
#line 1980 "kyrc.c"
}


static void main_instance_init (Main * self) {
	SqlClient* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	GraniteWidgetsSourceListExpandableItem* _tmp3_ = NULL;
	GraniteWidgetsSourceListExpandableItem* _tmp4_ = NULL;
	GraniteWidgetsSourceList* _tmp5_ = NULL;
#line 25 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv = MAIN_GET_PRIVATE (self);
#line 41 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = sql_client_get_instance ();
#line 41 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv->sqlclient = _tmp0_;
#line 44 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, gtk_text_view_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 44 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv->outputs = _tmp1_;
#line 45 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, TYPE_CLIENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 45 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv->clients = _tmp2_;
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = granite_widgets_source_list_expandable_item_new ("");
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = _tmp3_;
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = granite_widgets_source_list_new (_tmp4_);
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp5_);
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv->servers = _tmp5_;
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (_tmp4_);
#line 2017 "kyrc.c"
}


static void main_finalize (GObject* obj) {
	Main * self;
#line 25 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
#line 38 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->tabs);
#line 39 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->window);
#line 40 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->input);
#line 41 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->sqlclient);
#line 42 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->pannel);
#line 44 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->outputs);
#line 45 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->clients);
#line 46 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->servers);
#line 25 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
#line 2043 "kyrc.c"
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}



