/* kyrc.c generated by valac 0.26.2, the Vala compiler
 * generated from kyrc.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*-  */
/*
 * main.c
 * Copyright (C) 2015 Kyle Agronick <agronick@gmail.com>
 * 
 * KyRC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * KyRC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gio/gio.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define TYPE_CLIENT (client_get_type ())
#define CLIENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CLIENT, Client))
#define CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CLIENT, ClientClass))
#define IS_CLIENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CLIENT))
#define IS_CLIENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CLIENT))
#define CLIENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CLIENT, ClientClass))

typedef struct _Client Client;
typedef struct _ClientClass ClientClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _ClientPrivate ClientPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;

struct _Main {
	GObject parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GObjectClass parent_class;
};

struct _MainPrivate {
	GtkNotebook* tabs;
	GtkWindow* window;
	GtkEntry* input;
	GeeHashMap* outputs;
	GeeHashMap* clients;
};

struct _Client {
	GObject parent_instance;
	ClientPrivate * priv;
	GDataInputStream* input_stream;
	GDataOutputStream* output_stream;
	gint tab;
	gchar* username;
};

struct _ClientClass {
	GObjectClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	Main* self;
	GtkTextView* tv;
	gchar* data;
};


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
GType client_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY
};
#define MAIN_UI_FILE "src/kyrc.ui"
Main* main_new (void);
Main* main_construct (GType object_type);
static void ___lambda4_ (Main* self);
void main_send_text_out (Main* self, const gchar* text);
static void ____lambda4__gtk_entry_activate (GtkEntry* _sender, gpointer self);
void main_add_tab (Main* self, const gchar* url);
Client* client_new (void);
Client* client_construct (GType object_type);
void main_add_text (Main* self, gint index, const gchar* data);
static void _main_add_text_client_new_data (Client* _sender, gint index, const gchar* data, gpointer self);
gboolean client_connect_to_server (Client* self, const gchar* location, gint tab_page);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean __lambda5_ (Block1Data* _data1_);
static gboolean ___lambda5__gsource_func (gpointer self);
void client_send_output (Client* self, const gchar* output);
void main_on_destroy (GtkWidget* window, Main* self);
static gint main_main (gchar** args, int args_length1);
static void main_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return self ? g_object_ref (self) : NULL;
#line 131 "kyrc.c"
}


static void ___lambda4_ (Main* self) {
	GtkEntry* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GtkEntry* _tmp2_ = NULL;
#line 62 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->input;
#line 62 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gtk_entry_get_text (_tmp0_);
#line 62 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_send_text_out (self, _tmp1_);
#line 63 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = self->priv->input;
#line 63 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_entry_set_text (_tmp2_, "");
#line 149 "kyrc.c"
}


static void ____lambda4__gtk_entry_activate (GtkEntry* _sender, gpointer self) {
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	___lambda4_ ((Main*) self);
#line 156 "kyrc.c"
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	GError * _inner_error_ = NULL;
#line 44 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = (Main*) g_object_new (object_type, NULL);
#line 165 "kyrc.c"
	{
		GtkSettings* _tmp0_ = NULL;
		GtkBuilder* builder = NULL;
		GtkBuilder* _tmp1_ = NULL;
		GtkHeaderBar* toolbar = NULL;
		GtkHeaderBar* _tmp2_ = NULL;
		GObject* _tmp3_ = NULL;
		GtkWindow* _tmp4_ = NULL;
		GObject* _tmp5_ = NULL;
		GtkNotebook* _tmp6_ = NULL;
		GObject* _tmp7_ = NULL;
		GtkEntry* _tmp8_ = NULL;
		GtkEntry* _tmp9_ = NULL;
		GtkHeaderBar* _tmp10_ = NULL;
		GtkWindow* _tmp11_ = NULL;
		GtkHeaderBar* _tmp12_ = NULL;
		GtkWindow* _tmp13_ = NULL;
#line 49 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp0_ = gtk_settings_get_default ();
#line 49 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_set ((GObject*) _tmp0_, "gtk-application-prefer-dark-theme", TRUE, NULL);
#line 51 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp1_ = gtk_builder_new ();
#line 51 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		builder = _tmp1_;
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_builder_add_from_file (builder, MAIN_UI_FILE, &_inner_error_);
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 52 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
			_g_object_unref0 (builder);
#line 197 "kyrc.c"
			goto __catch0_g_error;
		}
#line 53 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_builder_connect_signals (builder, self);
#line 55 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp2_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 55 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_object_ref_sink (_tmp2_);
#line 55 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		toolbar = _tmp2_;
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp3_ = gtk_builder_get_object (builder, "window");
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp4_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp3_, gtk_window_get_type ()) ? ((GtkWindow*) _tmp3_) : NULL);
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->window);
#line 57 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->window = _tmp4_;
#line 58 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp5_ = gtk_builder_get_object (builder, "tabs");
#line 58 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp6_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, gtk_notebook_get_type ()) ? ((GtkNotebook*) _tmp5_) : NULL);
#line 58 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->tabs);
#line 58 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->tabs = _tmp6_;
#line 59 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp7_ = gtk_builder_get_object (builder, "input");
#line 59 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp8_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp7_, gtk_entry_get_type ()) ? ((GtkEntry*) _tmp7_) : NULL);
#line 59 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self->priv->input);
#line 59 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self->priv->input = _tmp8_;
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp9_ = self->priv->input;
#line 61 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_signal_connect_object (_tmp9_, "activate", (GCallback) ____lambda4__gtk_entry_activate, self, 0);
#line 66 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp10_ = toolbar;
#line 66 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_header_bar_set_show_close_button (_tmp10_, TRUE);
#line 67 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp11_ = self->priv->window;
#line 67 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp12_ = toolbar;
#line 67 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_window_set_titlebar (_tmp11_, (GtkWidget*) _tmp12_);
#line 69 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp13_ = self->priv->window;
#line 69 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		gtk_widget_show_all ((GtkWidget*) _tmp13_);
#line 72 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		main_add_tab (self, "irc.freenode.net");
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (toolbar);
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (builder);
#line 256 "kyrc.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp14_ = NULL;
		GError* _tmp15_ = NULL;
		const gchar* _tmp16_ = NULL;
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		e = _inner_error_;
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_inner_error_ = NULL;
#line 76 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp14_ = stderr;
#line 76 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp15_ = e;
#line 76 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_tmp16_ = _tmp15_->message;
#line 76 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		fprintf (_tmp14_, "Could not load UI: %s\n", _tmp16_);
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_error_free0 (e);
#line 279 "kyrc.c"
	}
	__finally0:
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_clear_error (&_inner_error_);
#line 47 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		return NULL;
#line 290 "kyrc.c"
	}
#line 44 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return self;
#line 294 "kyrc.c"
}


Main* main_new (void) {
#line 44 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return main_construct (TYPE_MAIN);
#line 301 "kyrc.c"
}


static void _main_add_text_client_new_data (Client* _sender, gint index, const gchar* data, gpointer self) {
#line 98 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_add_text ((Main*) self, index, data);
#line 308 "kyrc.c"
}


void main_add_tab (Main* self, const gchar* url) {
	GtkLabel* title = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkScrolledWindow* scrolled = NULL;
	GtkScrolledWindow* _tmp2_ = NULL;
	GtkTextView* output = NULL;
	GtkTextView* _tmp3_ = NULL;
	gint index = 0;
	GtkNotebook* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	GeeHashMap* _tmp6_ = NULL;
	GtkWindow* _tmp7_ = NULL;
	Client* client = NULL;
	Client* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	GeeHashMap* _tmp10_ = NULL;
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (url != NULL);
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = url;
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp1_);
#line 83 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	title = _tmp1_;
#line 84 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 84 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp2_);
#line 84 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	scrolled = _tmp2_;
#line 85 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = (GtkTextView*) gtk_text_view_new ();
#line 85 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_ref_sink (_tmp3_);
#line 85 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	output = _tmp3_;
#line 86 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_text_view_set_wrap_mode (output, GTK_WRAP_WORD);
#line 87 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_container_add ((GtkContainer*) scrolled, (GtkWidget*) output);
#line 89 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = self->priv->tabs;
#line 89 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = gtk_notebook_append_page (_tmp4_, (GtkWidget*) scrolled, (GtkWidget*) title);
#line 89 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	index = _tmp5_;
#line 90 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = self->priv->outputs;
#line 90 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp6_, (gpointer) ((gintptr) index), output);
#line 92 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp7_ = self->priv->window;
#line 92 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp7_);
#line 94 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp8_ = client_new ();
#line 94 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client = _tmp8_;
#line 95 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp9_ = g_strdup ("kyle123456");
#line 95 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_free0 (client->username);
#line 95 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client->username = _tmp9_;
#line 96 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp10_ = self->priv->clients;
#line 96 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gee_abstract_map_set ((GeeAbstractMap*) _tmp10_, (gpointer) ((gintptr) index), client);
#line 98 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_signal_connect_object (client, "new-data", (GCallback) _main_add_text_client_new_data, self, 0);
#line 99 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client_connect_to_server (client, "irc.freenode.net", index);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (client);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (output);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (scrolled);
#line 81 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (title);
#line 397 "kyrc.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return _data1_;
#line 406 "kyrc.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 415 "kyrc.c"
		Main* self;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		self = _data1_->self;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (_data1_->tv);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_free0 (_data1_->data);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		_g_object_unref0 (self);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
		g_slice_free (Block1Data, _data1_);
#line 427 "kyrc.c"
	}
}


static gboolean __lambda5_ (Block1Data* _data1_) {
	Main* self;
	gboolean result = FALSE;
	GtkTextBuffer* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkTextBuffer* _tmp2_ = NULL;
	GtkTextBuffer* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
#line 105 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = _data1_->self;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = gtk_text_view_get_buffer (_data1_->tv);
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = _tmp0_;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = gtk_text_view_get_buffer (_data1_->tv);
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = _tmp2_;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_get (_tmp3_, "text", &_tmp4_, NULL);
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = _tmp4_;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp6_ = _tmp5_;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp7_ = _data1_->data;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp8_ = g_strconcat (_tmp6_, _tmp7_, NULL);
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp9_ = _tmp8_;
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_object_set (_tmp3_, "text", _tmp9_, NULL);
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_free0 (_tmp9_);
#line 106 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_free0 (_tmp6_);
#line 107 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = FALSE;
#line 107 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 477 "kyrc.c"
}


static gboolean ___lambda5__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda5_ (self);
#line 105 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 486 "kyrc.c"
}


void main_add_text (Main* self, gint index, const gchar* data) {
	Block1Data* _data1_;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	GeeHashMap* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gpointer _tmp4_ = NULL;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (data != NULL);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->_ref_count_ = 1;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->self = g_object_ref (self);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = data;
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_free0 (_data1_->data);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->data = _tmp1_;
#line 104 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = self->priv->outputs;
#line 104 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = index;
#line 104 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, (gpointer) ((gintptr) _tmp3_));
#line 104 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_->tv = (GtkTextView*) _tmp4_;
#line 105 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda5__gsource_func, block1_data_ref (_data1_), block1_data_unref);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	block1_data_unref (_data1_);
#line 102 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_data1_ = NULL;
#line 529 "kyrc.c"
}


void main_send_text_out (Main* self, const gchar* text) {
	gint page = 0;
	GtkNotebook* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	GeeHashMap* _tmp2_ = NULL;
	gpointer _tmp3_ = NULL;
	Client* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
#line 111 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 111 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (text != NULL);
#line 113 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = self->priv->tabs;
#line 113 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gtk_notebook_get_current_page (_tmp0_);
#line 113 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	page = _tmp1_;
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp2_ = self->priv->clients;
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp3_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp2_, (gpointer) ((gintptr) page));
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp4_ = (Client*) _tmp3_;
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp5_ = text;
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	client_send_output (_tmp4_, _tmp5_);
#line 114 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (_tmp4_);
#line 563 "kyrc.c"
}


void main_on_destroy (GtkWidget* window, Main* self) {
#line 118 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (self != NULL);
#line 118 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_return_if_fail (window != NULL);
#line 120 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_main_quit ();
#line 574 "kyrc.c"
}


static gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	Main* app = NULL;
	Main* _tmp0_ = NULL;
#line 125 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_init (&args_length1, &args);
#line 126 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = main_new ();
#line 126 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	app = _tmp0_;
#line 128 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	gtk_main ();
#line 130 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	result = 0;
#line 130 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (app);
#line 130 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return result;
#line 596 "kyrc.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 123 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	return main_main (argv, argc);
#line 606 "kyrc.c"
}


static void main_class_init (MainClass * klass) {
#line 24 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	main_parent_class = g_type_class_peek_parent (klass);
#line 24 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	g_type_class_add_private (klass, sizeof (MainPrivate));
#line 24 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
#line 617 "kyrc.c"
}


static void main_instance_init (Main * self) {
	GeeHashMap* _tmp0_ = NULL;
	GeeHashMap* _tmp1_ = NULL;
#line 24 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv = MAIN_GET_PRIVATE (self);
#line 40 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp0_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, gtk_text_view_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 40 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv->outputs = _tmp0_;
#line 41 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_tmp1_ = gee_hash_map_new (G_TYPE_INT, NULL, NULL, TYPE_CLIENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 41 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self->priv->clients = _tmp1_;
#line 634 "kyrc.c"
}


static void main_finalize (GObject* obj) {
	Main * self;
#line 24 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN, Main);
#line 36 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->tabs);
#line 37 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->window);
#line 38 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->input);
#line 40 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->outputs);
#line 41 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	_g_object_unref0 (self->priv->clients);
#line 24 "/home/stack/Apps/projects/KyRC/src/kyrc.vala"
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
#line 654 "kyrc.c"
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (G_TYPE_OBJECT, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}



